version: '3.7'

#### POSTGRES ####################################################
services:
  postgres:
    image: postgres:12.20-alpine3.20
    container_name: postgres-aston
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
#### JAVA ####################################################
  app-course-aston:
    image: fomabb/app-course-aston:v.0.0.1
    container_name: app-course-aston
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres