create table if not exists baseentity
(
    id bigint not null
        primary key
);

alter table if exists baseentity
    owner to postgres;

-- Создание таблицы Course
CREATE TABLE if not exists course
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Создание таблицы Teacher
CREATE TABLE if not exists teacher
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    status    character varying(10),
    course_id BIGINT,
    FOREIGN KEY (course_id) REFERENCES course (id)
);

-- Создание таблицы Student
CREATE TABLE if not exists student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    status     character varying(10),
    teacher_id BIGINT,
    FOREIGN KEY (teacher_id) REFERENCES teacher (id)
);

-- Создание промежуточной таблицы для связи Many-to-Many между Student и Course
CREATE TABLE if not exists student_course
(
    student_id BIGINT,
    course_id  BIGINT,
    PRIMARY KEY (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES student (id),
    FOREIGN KEY (course_id) REFERENCES course (id)
);